### ISSUE TITLE
OBOE: Map randomisation

### ISSUE THREAD

**Issue by vicr123** [VilleOlof/MineGuessr#8]
There is an OBOE in the code that picks a random map

https://github.com/VilleOlof/MineGuessr/blob/bc8ca35193a4db2bd701aae05ac07eba7e1f984d/src/routes/play/%2Bpage.server.ts#L38

This OBOE will be triggered 100% of the time if you only have 5 maps and it's because `Math.random()` gives a number from 0 inclusive to 1 exclusive - and that means that the code that's currently written has the ability to return -1 as an index.

It's possible that the line above also has this but I haven't checked :)

**Comment by VilleOlof** [comment]
Huh, How can this even be an issue?
This random variable gets thrown into `get_random_locations` which itself has a check for if amount is greater than `possible_locations.length` (https://github.com/VilleOlof/MineGuessr/blob/bc8ca35193a4db2bd701aae05ac07eba7e1f984d/src/lib/server/locations.ts#L15) And the constant for rounds per match is 5. So there must be at least 5 possible locations for the game to even function since it has to populate every round of one game.

**Comment by vicr123** [comment]
Given `possible_locations.length` = 5, and a possible `Math.random()` = 0, we calculate:

Math.floor(0 × 5 - 1)
-> Math.floor(0 - 1)
-> Math.floor(-1)
which results in the function returning -1

**Comment by VilleOlof** [comment]
Oh yeah that totally makes sense now wow. Good find!
Maybe im just silly right now but couldnt this easily be fixed with just doing `(Math.random() * (possible_locations.length - 1))`
So if Math.random() is 0 it will never get -1 since the length will do that first?

**Comment by vicr123** [comment]
I think the correct solution is just to remove the -1, since `Math.random()` will never return 1 :)

**Comment by VilleOlof** [comment]
If you are able to test it out (Probably also with the `unsafeUniformIntDistribution` above if possible) and make a pull request i would happily merge it. Otherwise i could probably take a look on fixing it tomorrow or so

**Comment by vicr123** [comment]
I'll double check and open a PR if I find some time :)
